### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by allrude** [laraone/laraone#4]
Hi I installed it with the given instructions, first thing that went wrong is dat it didn't  make a .env file as described i had to manually copy and rename the example, now that not a real problem, perhase just a flaw in the documentation, what is a dealbreaker is that after installation the admin made in the .env isn't in the DB.

So i added the admin manually to the DB, but still couldn't login, changing the password on the existing users also doesn't work.

**Comment by HarisDev** [comment]
Changing existing super admin password to one generated at [https://bcrypt-generator.com](https://bcrypt-generator.com) worked for me.

**Comment by nikocraft** [comment]
I've updated the installation guide: https://laraone.dev/docs/developer/start/installation

I'm still working on the part where I explain better what happens when you install locally by running 
        
    php artisan laraone:install

I've updated the guide to use the graphical install wizard.
